### ISSUE TITLE
new Sygma and Kripo nodes default to Python3

### ISSUE THREAD

**Issue by sverhoeven** [sverhoeven/packer-test#29]
The Python packages for Sygma and Kripo are now installed in Python2. The KNIME-Python plugin defaults to Python3.

So either
1. Install Sygma+Kripodb+rdkit+pandas+numpy in Python3
2. Adjust KNIME config to default to Python2. In `workspace/.metadata/.plugins/org.eclipse.core.runtime/.settings/org.knime.python2.prefs` set `defaultPythonOption=python2`

**Comment by sverhoeven** [comment]
KNIME in VM has been configured to default to Python 2

**Comment by sverhoeven** [comment]
When opening workflow with SyGMA node cause the following error
```
2018-02-08 09:31:38,014 : DEBUG : ModalContext : FileWorkflowPersistor : SyGMA-example : 0 : Unable to load node with ID suffix 1 into workflow, skipping it: No default python version available from preference page!
java.lang.IllegalStateException: No default python version available from preference page!
        at org.knime.python2.kernel.PythonKernelOptions.getPreferencePythonVersion(PythonKernelOptions.java:330)
        at org.knime.python2.kernel.PythonKernelOptions.<init>(PythonKernelOptions.java:86)
        at nl.esciencecenter.e3dchem.python.PythonWrapperNodeConfig.<init>(PythonWrapperNodeConfig.java:36)
        at nl.esciencecenter.e3dchem.python.PythonWrapperNodeConfig.<init>(PythonWrapperNodeConfig.java:43)
        at nl.esciencecenter.e3dchem.sygma.PredictMetabolitesConfig.<init>(PredictMetabolitesConfig.java:35)
        at nl.esciencecenter.e3dchem.sygma.PredictMetabolitesModel.createConfig(PredictMetabolitesModel.java:39)
        at nl.esciencecenter.e3dchem.sygma.PredictMetabolitesModel.createConfig(PredictMetabolitesModel.java:1)
        at nl.esciencecenter.e3dchem.python.PythonWrapperNodeModel.<init>(PythonWrapperNodeModel.java:34)
        at nl.esciencecenter.e3dchem.sygma.PredictMetabolitesModel.<init>(PredictMetabolitesModel.java:33)
        at nl.esciencecenter.e3dchem.sygma.PredictMetabolitesFactory.createNodeModel(PredictMetabolitesFactory.java:18)
        at nl.esciencecenter.e3dchem.sygma.PredictMetabolitesFactory.createNodeModel(PredictMetabolitesFactory.java:1)
        at org.knime.core.node.NodeFactory.callCreateNodeModel(NodeFactory.java:481)
        at org.knime.core.node.Node.<init>(Node.java:263)
        at org.knime.core.node.Node.<init>(Node.java:253)
        at org.knime.core.node.workflow.FileNativeNodeContainerPersistor.preLoadNodeContainer(FileNativeNodeContainerPersistor.java:210)
        at org.knime.core.node.workflow.FileWorkflowPersistor.loadNodeContainer(FileWorkflowPersistor.java:1038)
        at org.knime.core.node.workflow.WorkflowManager.postLoad(WorkflowManager.java:7855)
        at org.knime.core.node.workflow.WorkflowManager.loadContent(WorkflowManager.java:7746)
        at org.knime.core.node.workflow.WorkflowManager.load(WorkflowManager.java:7700)
        at org.knime.core.node.workflow.WorkflowManager.load(WorkflowManager.java:7621)
        at org.knime.core.node.workflow.WorkflowManager.load(WorkflowManager.java:7594)
        at org.knime.core.node.workflow.WorkflowManager.loadProject(WorkflowManager.java:7439)
        at org.knime.workbench.editor2.LoadWorkflowRunnable.run(LoadWorkflowRunnable.java:168)
        at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:119)
```

The workflow is loaded, but the SyGMA node is missing.
